---
title: "Anacapa in R Testing"
author: "Ella Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: purple
---

# [Documentation Link](https://github.com/gauravsk/ranacapa)

# Setup

- `BiocManager::install("multtest")`
- `BiocManager::install("phyloseq")`
- Install devtools
- `devtools::install_github("gauravsk/ranacapa")`
- There is also a terminal option if desired

```{r Install Package}
library(devtools)
library(ranacapa)
```

# What is Anacapa?

- Input file: Anacapa output file, aka biom file
  - One column of full taxonomic path, one column for each sample, sometimes one column for unique sequence identifiers (this identifier is useful only if you need to go back to a FASTA file and find the sequence)
- Other input file: Mapping file with the sample metadata. The first column values must match the sample names (Anacapa output column names)

The main purpose of `ranacapa` is to convert between Anacapa output and `phyloseq` objects

# Anacapa Functions

- `group_anacapa_by_taxonomy()` If two rows have the same taxonomic path, group those rows and add up the sample column values. This cleans duplicates for phyloseq.
- `convert_anacapa_to_phyloseq()` does what it says on the tin, requiring two input files (Anacapa output and mapping file) and spitting out one `phyloseq` object
  - Note: Phyloseq is a package and an object class