---
title: "“OCNMS CTD Data Exploration”"
author: "Eleanor (Ella) Crotty"
header-includes: \usepackage{fvextra} \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    toc: yes
urlcolor: blue
---

# Setup

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork) # Put plots together
library(scales) # Rescale datetime axes
library(ggrepel)
library(readxl)
library(here) # Project/filepath management
library(maps)
library(RColorBrewer) # Color palettes
library(colorRamps) # Color palettes
```

```{r Data Imports}
wd <- "OCNMS_Hypoxia/Data/CTD_Data"
exp <- "OCNMS_Hypoxia/Outputs"
pltpath <- "OCNMS_Hypoxia/Plots/CTD_Data_Exploration_Plots"

# read_csv(csv, col_types = cols(date = col_date("%m/%d/%y")))
# Format is %Y-%m-%eT%H:%M:%SZ
OME_CTD <- read.csv(here(wd, "OCNMS_OME_ctd_output_copy.csv"))
OCNMS_OME_CTD <- read.csv(here(wd, "OCNMS_OMEsites_ctd_output_copy.csv"))
OCNMS_All_CTD <- read.csv(here(wd, "OCNMS_Allsites_ctd_output_copy.csv"))

OME_CTD$date = as.Date(OME_CTD$date, tryFormats = c("%Y-%m-%d"))
OCNMS_OME_CTD$date = as.POSIXct(OCNMS_OME_CTD$date, tryFormats = c("%Y-%m-%dT%H:%M:%SZ"), tz = "UTC")
OCNMS_All_CTD$date = as.POSIXct(OCNMS_All_CTD$date, tryFormats = c("%Y-%m-%dT%H:%M:%SZ"), tz = "UTC")

# Problem: all the longitudes are positive, they need to be negative
fixlong <- function(df) {
  df$longitude <- df$longitude*-1
  df
}

head(fixlong(OME_CTD))

OME_CTD <- fixlong(OME_CTD)
OCNMS_OME_CTD <- fixlong(OCNMS_OME_CTD)
OCNMS_All_CTD <- fixlong(OCNMS_All_CTD)
# All better!

# Problem #2: OME used oxygen, OCNMS uses dissolved_oxygen
OCNMS_All_CTD <- OCNMS_All_CTD %>% 
  rename(DO = dissolved_oxygen)
OCNMS_OME_CTD <- OCNMS_OME_CTD %>% 
  rename(DO = dissolved_oxygen)
OME_CTD <- OME_CTD %>% 
  rename(DO = oxygen)
```

```{r Mapping Setup}
mapUC <- map_data("world", region = c("usa", "canada"))

ggplot(mapUC, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "gray90", color = "black") +
  coord_sf() # coord_quickmap is an approximation to preserve straight lines, which works best for small areas close to the equator. projection can be defined (see mapproj::mapproject() for list) and R now recommends using coord_sf(). coord_sf() takes xlim, ylim, crs
```

## Some excerpts from the R for Data Science tutorial

```
nz <- map_data("nz")

ggplot(nz, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap() # This will fix the weird stretch usually
```

```
# Making a ggplot with label changes
histogram <- function(df, var, binwidth) {
  label <- rlang::englue("A histogram of {{var}} with binwidth {binwidth}")
  
  df |> 
    ggplot(aes(x = {{ var }})) + 
    geom_histogram(binwidth = binwidth) + 
    labs(title = label)
}

diamonds |> histogram(carat, 0.1)
diamonds |> histogram(price, 1000)
```

```
df <- tribble(
  ~id, ~measurement, ~value,
  "A",        "bp1",    100,
  "B",        "bp1",    140,
  "B",        "bp2",    115, 
  "A",        "bp2",    120,
  "A",        "bp3",    105
)
```

# Functions

```{r Map Function}
# Variable to make a base map of OCNMS, which I can then add data points to

rangeOC <- tribble(
  ~MinLong, ~MaxLong, ~MinLat, ~MaxLat,
  min(OME_CTD$longitude), max(OME_CTD$longitude), min(OME_CTD$latitude), max(OME_CTD$latitude)
)

OCNMS_x <- c(-123.5, -125.5)
OCNMS_y <- c(47,49)

mapOCNMS <- ggplot(mapUC, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "gray90", color = "black") +
  coord_sf(xlim = OCNMS_x, 
           ylim = OCNMS_y) +
  theme_bw() +
  theme(text = element_text(size=15),
        panel.background = element_rect(fill = "azure1", 
                                        colour = "azure1"),
        legend.key = element_rect(fill = "white",
                                         color = "white"),
        # It added in blue behind the dots in the key and I don't want that
        panel.grid.major = element_line(size = 0.5, 
                                        linetype = 'solid', 
                                        colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid', 
                                        colour = "white")) # +
  # coord_quickmap() # This will fix the weird stretch usually, can also do coord_fixed(ratio = 1.3)

mapOCNMS

mapOCNMS +
  geom_point(data = OME_CTD, aes(x = longitude, y = latitude, group = NA)) + # aes(group = NA) or geom_point(inherit = FALSE) keeps it from looking for a group since the base layer has groups 
  ggtitle("OME CTD Locations")

# Just checking to make sure this is the same
mapOCNMS +
  geom_point(data = OCNMS_OME_CTD, aes(x = longitude, y = latitude, group = NA)) + # aes(group = NA) or geom_point(inherit = FALSE) keeps it from looking for a group since the base layer has groups 
  ggtitle("OCNMS OME CTD Locations")

mapOCNMS +
  geom_point(data = OCNMS_All_CTD, aes(x = longitude, y = latitude, group = NA)) + # aes(group = NA) or geom_point(inherit = FALSE) keeps it from looking for a group since the base layer has groups 
  geom_point(data = OME_CTD, aes(x = longitude, y = latitude, group = NA), color = "cornflowerblue") +
  labs(title = "All OCNMS CTD Locations", caption = "**OME Sampling Sites in Blue", x = "Longitude", y = "Latitude")

ggsave("CTD_Locations.png", path = here(pltpath), dpi = 500)
```

```{r Histogram Functions}
# Histogram function
histogram_fill <- function(df, var, binwidth, fill = "darkgray") {
  label <- rlang::englue("A histogram of {{var}} in {{df}} with binwidth {binwidth}")
  
  df |> 
    ggplot(aes(x = {{ var }}, fill = {{fill}})) + 
    geom_histogram(binwidth = binwidth, color = "black") + 
    labs(title = label) +
    theme_bw()
}

histogram2 <- function(df, var, binwidth, fill = NA) { # Not currently functional
  label <- rlang::englue("A histogram of {{var}} in {{df}} with binwidth {binwidth}")
  
  if (is.na(fill)) {
    df |> 
    ggplot(aes(x = {{ var }})) + 
    geom_histogram(binwidth = binwidth, color = "black", fill = "darkgray") + 
    labs(title = label) +
    theme_bw()
  } else {
  df |> 
    ggplot(aes(x = {{ var }}, fill = {{fill}})) + 
    geom_histogram(binwidth = binwidth, color = "black") + 
    labs(title = label) +
    theme_bw()
  }
  
}

histogram <- function(df, var, binwidth) {
  label <- rlang::englue("A histogram of {{var}} in {{df}} with binwidth {binwidth}")
  
  df |> 
    ggplot(aes(x = {{ var }})) + 
    geom_histogram(binwidth = binwidth, color = "black", fill = "darkgray") + 
    labs(title = label) +
    theme_bw()
}
```

```{r Scatterplot Functions}
scatterplt <- function(df, x, y, shape = 16, alpha = 1) {
  label <- rlang::englue("A scatterplot of {{x}} vs {{y}} in {{df}}")
  
  df |> 
    ggplot(aes(x = {{ x }}, y = {{ y }})) + 
    geom_point(color = "blue", shape = shape, alpha = alpha) + 
    labs(title = label) +
    theme_bw()
}

scatterplt_fill <- function(df, x, y, color, shape = 16, alpha = 1) {
  label <- rlang::englue("A scatterplot of {{x}} vs {{y}} in {{df}}")
  
  df |> 
    ggplot(aes(x = {{ x }}, y = {{ y }}, color = {{ color }})) + 
    geom_point(shape = shape, alpha = alpha) + 
    labs(title = label) +
    theme_bw()
}
```


# Cleaning

## Add dates & years
```{r Investigate year distribution}
# Dates are chr "2005-05-25T22:48:33Z"
# tryFormats = c("%Y-%m-%eT%H:%M:%SZ")
# Moving the as.POSIXCT call to import - col_types = cols(date = col_date("%m/%d/%y"))

OME_CTD <- OME_CTD %>% 
  # mutate(date = as.POSIXct(date, tryFormats = c("%Y-%m-%dT%H:%M:%SZ"))) %>% 
  mutate(year = as.factor(year(date)))

OME_CTD %>% 
  group_by(year) %>% 
  summarize(Observations_OME = n())

OCNMS_OME_CTD <- OCNMS_OME_CTD %>% 
  # mutate(date = as.POSIXct(date)) %>% 
  mutate(year = as.factor(year(date)))

OCNMS_OME_CTD %>% 
  group_by(year) %>% 
  summarize(Observations_OCNMS_filtOME = n())

OCNMS_All_CTD <- OCNMS_All_CTD %>% 
  # mutate(date = as.POSIXct(date)) %>% 
  mutate(year = as.factor(year(date)))

OCNMS_All_CTD %>% 
  group_by(year) %>% 
  summarize(Observations_OCNMS = n())
```
## DO Clean
```{r OME vs. OCNMS}
# Why is some of it negative???
histogram_fill(OME_CTD, DO, 0.5, fill = station_name)
histogram_fill(OME_CTD, DO, 0.5, fill = year)
histogram_fill(OME_CTD, DO, 0.5, fill = as.factor(month(date)))
# Shannon says the OME files are redundant and the OCNMS published data probably just eliminated that because the quality score was low or something. Shannon will check with Sam. Use OCNMS_OME_CTD for now. 

# Plot OME vs. OCNMS to see if redundant
ggplot(OCNMS_OME_CTD, aes(x = as.Date(date), y = DO)) +
  geom_point(shape = 1, color = "blue") +
  theme_bw() +
  geom_point(data = OME_CTD, aes(x = date, y = DO), color = "yellow", shape = 1)
# Probably redundant, OME is the only one with 2024 though
```
## General Cleaning

### Histograms
```{r}
histogram_fill(OCNMS_OME_CTD, depth, 1, fill = year)
histogram_fill(OCNMS_OME_CTD, depth, 1, fill = station_id)
histogram_fill(OCNMS_OME_CTD, temperature, 1, fill = year)
histogram_fill(OCNMS_OME_CTD, temperature, 1, fill = station_id)
histogram_fill(OCNMS_OME_CTD, salinity, 1, fill = year)
histogram_fill(OCNMS_OME_CTD, potential_density, 1, fill = year)
histogram_fill(OCNMS_OME_CTD, DO, 1, fill = year)
histogram_fill(OCNMS_OME_CTD, DO, 0.25, fill = station_id)
```

```{r General Cleaning}
# While plotting depth, I found 2 rows with depths of -9999 and several other NA values. Remove.
OCNMS_OME_CTD <- OCNMS_OME_CTD %>% 
  filter(depth > 0) # This removes 2 rows with NA values + -9999 depth

histogram_fill(OCNMS_OME_CTD, depth, 1, fill = year)
```

### Scatterplots
```{r Scatterplots}
scatterplt(OCNMS_OME_CTD, depth, potential_density, alpha = 0.1)
scatterplt_fill(OCNMS_OME_CTD, depth, potential_density, color = year)

scatterplt(OCNMS_OME_CTD, temperature, salinity, alpha = 0.1)
scatterplt_fill(OCNMS_OME_CTD, temperature, salinity, color = year)

# Check to make sure that 30-45 meters is an OK range to take data from and assume it's all about the same

CTD_2021to2023 <- OCNMS_OME_CTD %>% 
  filter(year %in% c(2021, 2022, 2023))

DOdepth <- scatterplt_fill(CTD_2021to2023, 
                           depth, 
                           DO, 
                           alpha = 0.5, 
                           color = station_id) +
  scale_color_manual(values = c("gray80", "blue")) +
  geom_vline(xintercept = 30)

DOdepthFacet <- scatterplt_fill(CTD_2021to2023, 
                                depth, 
                                DO, 
                                alpha = 0.5, 
                                color = station_id) +
  scale_color_manual(values = c("gray80", "blue")) +
  facet_wrap(facets = vars(year)) +
  geom_vline(xintercept = 30)

DOdepth / DOdepthFacet
ggsave(here(pltpath, "Depth_DO_Scatterplot_CTD_full.png"))

TempDepth <- scatterplt_fill(CTD_2021to2023, 
                depth, 
                temperature, 
                alpha = 0.5, 
                color = station_id) +
  scale_color_manual(values = c("gray80", "blue")) +
  geom_vline(xintercept = 30)

TempDepthFacet <- scatterplt_fill(CTD_2021to2023, 
                depth, 
                temperature, 
                alpha = 0.5, 
                color = station_id) +
  scale_color_manual(values = c("gray80", "blue")) +
  facet_wrap(facets = vars(year)) +
  geom_vline(xintercept = 30)

TempDepth / TempDepthFacet
ggsave(here(pltpath, "Depth_Temp_Scatterplot_CTD_full.png"))

# What's up with that weirdly non-stratified cast??
# It's in 2023
scatterplt_fill(CTD_2021to2023 %>% filter(year == 2023), 
                depth, 
                temperature, 
                alpha = 0.5, 
                color = sampleID) +
  geom_vline(xintercept = 30)

scatterplt_fill(CTD_2021to2023 %>% filter(year == 2023), 
                depth, 
                DO, 
                alpha = 0.5, 
                color = sampleID) +
  geom_vline(xintercept = 30)
# 2023-09-28 and 2023-09-29

# Check it out by month - hotter?
scatterplt_fill(CTD_2021to2023 %>% filter(station_id == "TH042"), 
                                depth, 
                                DO, 
                                alpha = 0.5, 
                                color = as.factor(month(date))) +
  facet_wrap(facets = vars(year)) +
  geom_vline(xintercept = 30) +
  ggtitle("Depth vs. DO in 2021-2023 CTD Casts")
ggsave(here(pltpath, "Depth_DO_Scatterplot_CTD_YearMonth.png"))

scatterplt_fill(CTD_2021to2023 %>% filter(station_id == "TH042"), 
                                depth, 
                                temperature, 
                                alpha = 0.5, 
                                color = as.factor(month(date))) +
  facet_wrap(facets = vars(year)) +
  geom_vline(xintercept = 30) +
  ggtitle("Depth vs. Temp in 2021-2023 CTD Casts")
ggsave(here(pltpath, "Depth_Temp_Scatterplot_CTD_YearMonth.png"))
# It wasn't like that in September 2022!
```


# Oxygen Data Exploration

## Histograms
```{r Oxygen Histograms}
histogram(OCNMS_All_CTD, DO, 0.5)

histogram(OCNMS_All_CTD, DO, 0.5) +
  facet_wrap(facets = vars(year))

histogram_fill(OCNMS_All_CTD, DO, 0.5, fill = year) 

histogram(OCNMS_OME_CTD, DO, 0.5)
```

# Time Series

```{r Line Plots}
# Goal: One line plot per year of dissolved oxygen versus date

# Graph of depth, oxygen level, and date by year
OCNMS_OME_CTD %>% 
  ggplot(aes(x = date, y = DO, color = depth)) +
    geom_point(shape = 1) +
    theme_bw() +
    facet_wrap(facets = vars(year), scales = "free_x", ncol = 1)
ggsave("OCNMS_CTD_Oxygen_FacetYear.png", path = here(pltpath), width = 1000, height = 5000, units = "px")

OCNMS_OME_CTD %>% 
  filter(year %in% c(2021, 2022, 2023)) %>% 
  ggplot(aes(x = date, y = DO, color = depth)) +
    geom_point(shape = 1) +
    theme_bw() +
    facet_wrap(facets = vars(year), scales = "free_x", ncol = 1)
ggsave("OCNMS_CTD_Oxygen_FacetYear_2020s.png", path = here(pltpath), width = 1500, height = 2000, units = "px")

# What depths do we have?
depths <- OCNMS_OME_CTD %>% 
  group_by(depth) %>% 
  summarize(n = n())
# Specific depths do repeat, but there are a few around 42 meters. Perhaps near(depth, 42, tol = 1)

ggplot(OCNMS_OME_CTD, aes(x = depth, fill = year)) +
  geom_histogram(binwidth = 1, color = "black") +
  scale_x_continuous(limits = c(30, 45), breaks = seq(from = 30, to = 45, by = 1)) +
  theme_bw()
ggsave("OCNMS_CTD_Depths.png", path = here(pltpath), width = 3000, height = 2000, units = "px")

# `if_else(condition, if_true_output, if_false_output, NA_val)` - used to transform vectors/data columns

# Logical vector of whether depth is within 1m of 42m
near42 <- near(OCNMS_OME_CTD$depth, 42, tol = 1)
sum(near42) # So the resulting DF should have 191 rows ***Not using this anymore

OCNMS_OME_CTD42m <- OCNMS_OME_CTD %>% # This is just for graphing, not exporting at the moment, because it also has the CE location
  filter(39.894 < depth) %>% 
  filter(depth < 44.898) # 401 observations, much better

# Graph of oxygen levels around 42 meters for each year
OCNMS_OME_CTD42m %>% 
  ggplot(aes(x = date, y = DO, color = depth)) +
    geom_line() +
    geom_point(shape = 1) +
    theme_bw() +
    facet_wrap(facets = vars(year), scales = "free_x", ncol = 1)
ggsave("OCNMS_CTD_Oxygen_FacetYear42m.png", path = here(pltpath), width = 1000, height = 5000, units = "px")
```

# Filter by depth

```{r}
OCNMS_OME_CTD_TH042 <- OCNMS_OME_CTD %>% 
  filter(39.894 < depth) %>% 
  filter(depth < 44.898)  %>% # 401 rows
  filter(station_id == "TH042") # 155 rows

OCNMS_OME_CTD_TH042_extended <- OCNMS_OME_CTD %>% 
  filter(30 < depth) %>% 
  filter(depth < 45)  %>% # 401 rows
  filter(station_id == "TH042") # 155 rows

OCNMS_OME_CTD_TH042 %>% 
  group_by(year) %>% 
  summarize(n = n(), MeanDepth = mean(depth))

OCNMS_OME_CTD_TH042_extended %>% 
  group_by(year) %>% 
  summarize(n = n(), MeanDepth = mean(depth))

# Graph of oxygen levels around 42 meters for each year
OCNMS_OME_CTD42m %>% 
  ggplot(aes(x = date, y = DO, color = depth)) +
    geom_line() +
    geom_point(shape = 1) +
    theme_bw() +
    facet_wrap(facets = vars(year), scales = "free_x", ncol = 1)
ggsave("OCNMS_CTD_Oxygen_FacetYearTH42m.png", path = here(pltpath), width = 1000, height = 5000, units = "px")
```

# Why no 2022/2023 data?

After filtering for TH042, I only have a few 2021 datapoints. Note 6/6: Fixed this by expanding to the range of the mooring, 39.894-44.898 meters deep.

```{r}
OCNMS_OME_CTD %>% 
  filter(year %in% c(2021, 2022, 2023)) %>% 
  group_by(year) %>% 
  summarize(n = n())
OCNMS_OME_CTD_TH042 %>% 
  filter(year %in% c(2021, 2022, 2023)) %>% 
  group_by(year) %>% 
  summarize(n = n())

histogram_fill(OCNMS_OME_CTD %>% filter(year %in% c(2021, 2022, 2023)), 
               depth, 
               1, 
               fill = station_id) +
  facet_wrap(facets = vars(year)) +
  labs(title = "Number of CTD datapoints at each depth", fill = "Station ID", x = "Depth", y = "# of Datapoints", caption = "42m is the depth of interest")

ggsave(here(pltpath, "WhyNo2022.png"), height = 2000, width = 3000, units = "px")
```


# Export

```{r Make CTD Data Compatible With Mooring Data}
# OCNMS_OME_CTD is the most useful to me at the moment, since it is clean and only contains the locations of interest
# Currently using OCNMS_OME_CTD_TH042. Need to average depth.
OCNMS_OME_CTD_TH042 %>% group_by(date) %>% summarize(depths = n()) # Not averaging many points per day

# Add + reorder columns to bind with mooring data
compatibility = function(df) {
  df$cond = NA
  df$pres = NA
  df$source = "CTD"
  x <- df %>% 
    select("source", "date", "year", "depth", "temperature", "DO", "salinity", "potential_density", "pres", "cond", "sampleID")
  return(x)
}

# OCNMS_OME_CTD_comptest <- compatibility(OCNMS_OME_CTD) # If this is equal to OCNMS_OME_CTD at the end of the chunk, the function works

#OCNMS_OME_CTD$cond = NA
#OCNMS_OME_CTD$pres = NA
#OCNMS_OME_CTD$source = "CTD"

OCNMS_OME_CTDexp <- compatibility(OCNMS_OME_CTD)
OCNMS_OME_CTD_TH042exp <- compatibility(OCNMS_OME_CTD_TH042)
OCNMS_OME_CTD_TH042_extended_exp <- compatibility(OCNMS_OME_CTD_TH042_extended)

OCNMS_OME_CTD_TH042exp <- OCNMS_OME_CTD_TH042exp %>% 
  group_by(source, date, year, sampleID) %>% 
  summarize(temperature = mean(temperature), 
            DO = mean(DO), 
            salinity = mean(salinity), 
            potential_density = mean(potential_density),
            pres = mean(pres),
            cond = mean(cond)) %>% 
  relocate(sampleID, .after = cond) # Now there is one row per day and no depth column

OCNMS_OME_CTD_TH042exp %>% group_by(date) %>% summarize(depths = n()) # Not averaging many points per day

OCNMS_OME_CTD_TH042_extended_exp <- OCNMS_OME_CTD_TH042_extended_exp %>% 
  group_by(source, date, year, sampleID) %>% 
  summarize(temperature = mean(temperature), 
            DO = mean(DO), 
            salinity = mean(salinity), 
            potential_density = mean(potential_density),
            pres = mean(pres),
            cond = mean(cond)) %>% 
  relocate(sampleID, .after = cond) # Now there is one row per day and no depth column

OCNMS_OME_CTD_TH042_extended_exp %>% group_by(date) %>% summarize(depths = n()) # Not averaging many points per day

# OCNMS_OME_CTDexp <- OCNMS_OME_CTD %>% select("source", "date", "year", "depth", "temperature", "DO", "salinity", "potential_density", "pres", "cond", "sampleID")
# OCNMS_OME_CTD_TH042exp <- OCNMS_OME_CTD_TH042 %>% select("source", "date", "year", "depth", "temperature", "DO", "salinity", "potential_density", "pres", "cond", "sampleID")

# head(OCNMS_OME_CTD_comptest == OCNMS_OME_CTD)
# mean(OCNMS_OME_CTD_comptest == OCNMS_OME_CTD, na.rm = T) # Mean of 1 = whole dataframe equal. compatibility() works!!!
```

```{r Export CTD Data}
write.csv(OCNMS_OME_CTDexp, file = here("OCNMS_Hypoxia", "Outputs", "OCNMS_CTD_CleanData.csv"))
write.csv(OCNMS_OME_CTD_TH042exp, file = here("OCNMS_Hypoxia", "Outputs", "OCNMS_CTD_TH042_CleanData.csv")) 
write.csv(OCNMS_OME_CTD_TH042_extended_exp, file = here("OCNMS_Hypoxia", "Outputs", "OCNMS_CTD_TH042ext_CleanData.csv")) # going to use this from here on out
```

