---
title: "Hypoxia Time Series Creation"
author: "Eleanor (Ella) Crotty"
header-includes: \usepackage{fvextra} \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    toc: yes
urlcolor: blue
---

Goal: Combine CTD and mooring data to assemble a hypoxia time series

Questions:

- Which depths can I use? Can I average them?
- What units is this dissolved oxygen data in?
- What is the hypoxic threshold? 

# Setup

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
```

```{r Data Imports}
wd <- "OCNMS_Hypoxia/Outputs"
exp <- "OCNMS_Hypoxia/Outputs"
pltpath <- "OCNMS_Hypoxia/Plots"

CTD_short <- read.csv(here(wd, "OCNMS_CTD_TH042_CleanData.csv")) %>% 
  mutate(date = as.POSIXct(date, tz = "UTC"), year = as.factor(year), source = as.factor(source)) # only 39.9-44.9 meters, not priority
CTD <- read.csv(here(wd, "OCNMS_CTD_TH042ext_CleanData.csv")) %>% 
  mutate(date = as.POSIXct(date, tz = "UTC"), year = as.factor(year), source = as.factor(source)) # priority
Mooring <- read.csv(here(wd, "OCNMS_Mooring_CleanData.csv")) %>% 
  mutate(date = as.POSIXct(date, tz = "UTC"), year = as.factor(year), source = as.factor(source))

# Group CTD casts together by sampleID (all depths) and average the environmental factors

EnvData1short <- rbind(CTD_short, Mooring) %>%    # 39.9 - 44.9 meters deep
  select(-X) %>% 
  mutate(year = as.factor(year), source = as.factor(source))

EnvData1 <- rbind(CTD, Mooring)  %>%    # 30-45 meters deep
  select(-X) %>% 
  mutate(year = as.factor(year), source = as.factor(source))
```


# Time Series (all years)

```{r Data Exploration All Years}
ctdplt <- ggplot(CTD, aes(x = date, y = DO)) +
  geom_point(color = "coral2") +
  scale_x_datetime(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw()
morplt <- ggplot(Mooring, aes(x = date, y = DO)) +
  geom_point(color = "turquoise3") +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()
plt1 <- ggplot(EnvData1, aes(x = date, y = DO, color = source)) +
  geom_point(shape = 1) +
  scale_x_datetime(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw()

(ctdplt / morplt / plt1) +
  plot_annotation(title = "CTD and Mooring Oxygen Data In OCNMS")

ggsave(here(pltpath, "CombinedOxygenSeries.png"), height = 2000, width = 3000, units = "px")

ctdplt2 <- ggplot(CTD, aes(x = date, y = temperature)) +
  geom_point(color = "coral2") +
  scale_x_datetime(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw()
morplt2 <- ggplot(Mooring, aes(x = date, y = temperature)) +
  geom_point(color = "turquoise3") +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()
plt12 <- ggplot(EnvData1, aes(x = date, y = temperature, color = source)) +
  geom_point(shape = 1) +
  scale_x_datetime(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw()

(ctdplt2 / morplt2 / plt12) +
  plot_annotation(title = "CTD and Mooring Temperature Data In OCNMS")

ggsave(here(pltpath, "CombinedTemperatureSeries.png"), height = 2000, width = 3000, units = "px")
```

# Time Series (2021-2023)

```{r Data Exploration post-2021}
CTD2 <- CTD %>% 
  filter(year %in% c(2021, 2022, 2023))
Mooring2 <- Mooring  %>% 
  filter(year %in% c(2021, 2022, 2023))
EnvData1_yr <- EnvData1  %>% 
  filter(year %in% c(2021, 2022, 2023))

ctdplt <- ggplot(CTD2, aes(x = date, y = DO)) +
  geom_point(color = "coral2") +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()
morplt <- ggplot(Mooring2, aes(x = date, y = DO)) +
  geom_point(color = "turquoise3") +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()
plt1 <- ggplot(EnvData1_yr, aes(x = date, y = DO, color = source)) +
  geom_point(shape = 1) +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()

(ctdplt / plt1) +
  plot_annotation(title = "CTD and Mooring Oxygen Data In OCNMS")

ggsave(here(pltpath, "CombinedOxygenSeries_crop.png"), height = 1000, width = 3000, units = "px")

ctdplt2 <- ggplot(CTD2, aes(x = date, y = temperature)) +
  geom_point(color = "coral2") +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()
morplt2 <- ggplot(Mooring2, aes(x = date, y = temperature)) +
  geom_point(color = "turquoise3") +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()
plt12 <- ggplot(EnvData1_yr, aes(x = date, y = temperature, color = source)) +
  geom_point(shape = 1) +
  scale_x_datetime(date_breaks = "2 months", date_labels = "%m-%y") +
  theme_bw()

(ctdplt2 / plt12) +
  plot_annotation(title = "CTD and Mooring Temperature Data In OCNMS")

ggsave(here(pltpath, "CombinedTemperatureSeries_crop.png"), height = 1000, width = 3000, units = "px")
```

```{r}
ggplot(EnvData1_yr, aes(x = date, y = temperature, color = source, shape = source)) +
  geom_point() +
  scale_shape_manual(values = c(19, 1)) +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m-%y") +
  theme_bw() +
  facet_wrap(facets = vars(year), scales = "free_x", ncol = 1)
```


```{r Export}
# Export EnvData1short (narrower depth range, full year range), EnvData1 (wider depth, full year), and EnvData1_yr (wider depth, 2021-2023)

write.csv(EnvData1short, file = here("OCNMS_Hypoxia", "Outputs", "EnvironmentalDataset1_Short_AllYears.csv"))
write.csv(EnvData1, file = here("OCNMS_Hypoxia", "Outputs", "EnvironmentalDataset1_AllYears.csv"))
write.csv(EnvData1_yr, file = here("OCNMS_Hypoxia", "Outputs", "EnvironmentalDataset1.csv")) # Mostly using this from here on out
write.csv(EnvData1_yr, file = here("OCNMS_Project", "Data", "EnvironmentalDataset1.csv"))
```

