---
title: “Mooring TH042 Data Exploration”
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

# Setup

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse) # ggplot, dplyr, lubridate, etc
library(patchwork) # put plots next to each other
library(scales) # ggplot enhancement
library(ggrepel) # ggplot enhancement
library(here) # Make nicer filepaths relative to this directory
library(R.matlab) # For checking against original mat files
```

```{r Data Imports}
# Set working directories (this will work within the PMEL-Hollings-eDNA-Hypoxia directory through the here() command)
wd <- "OCNMS_Hypoxia/Data"
exp <- "OCNMS_Hypoxia/Outputs"
pltpath <- "OCNMS_Hypoxia/Plots/Mooring_Data_Exploration_Plots"

TH042 <- read.csv(here(wd, "MooringData_CTPO_TH042.csv"), na = "NaN") # Import Teawhit Head 42m depth mooring data

TH042$time <- as.POSIXct(TH042$time, tryFormats = c("%e-%b-%Y %H:%M:%S"), tz = "UTC") # Convert time to POSIXct (datetime) class
TH042 <- TH042 %>%
  mutate(year = as.factor(year(time))) # Create year column
```

```{r, eval = F}
# Check times against .mat files
# This chunk is a pain in the neck and does not need to be run again, but if you feel like checking against the mooring matlab files, go ahead

MoorMat21 <- readMat(here("OCNMS_Hypoxia", "Data", "2021.mat"))
# str(MoorMat21) # Data structure
lst <- MoorMat21$CT.CA042.210610.038 # Extract data structure

lst[[1]][[4]][[4]][[1]] # well there's a julian time SOMEWHERE i guess

# as.POSIXct(86400*10625.15, origin=as.Date("1990-01-01 00:00:00"))
# 86400 = seconds in a Julian day
# 10625.15 is the Julian date in the example
lst[[1]][[2]][[65]]
lst[[1]][[2]][[66]]
lst[[1]][[2]][[67]]
lst[[1]][[2]][[68]]

matdates <- lst[[2]][[4]] # I think this is the Julian date
#as.POSIXct(86400*matdates, origin=as.Date("1990-01-01 00:00:00"))
# well THAT didn't fucking work
# let's try the stupid deprecated datenum thing
dateref <- as.data.frame(as.POSIXct((matdates - 719529)*86400, origin = "1970-01-01", tz = "UTC")) # subtract to get origin = January 0, 0000 (this is a made up date so as.POSIXct won't handle it natively), need to multiply by seconds in a day to go from datenum (days since made up Matlab epoch) to POSIXct (seconds since Unix epoch). Just kinda hoping they were using UTC here.
colnames(dateref) <- "Date"
# Somehow the CSV file has 27 seconds added to everything. I have elected to ignore that for the time being because it is small.
```


# Functions

```{r Map Function}
# Variable to make a base map of OCNMS, which I can then add data points to
mapUC <- map_data("world", region = c("usa", "canada"))
OCNMS_x <- c(-123.5, -125.5)
OCNMS_y <- c(47,49)

mapOCNMS <- ggplot(mapUC, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "gray90", color = "black") +
  coord_sf(xlim = OCNMS_x, 
           ylim = OCNMS_y) +
  theme_bw() +
  theme(text = element_text(size=15),
        panel.background = element_rect(fill = "azure1", 
                                        colour = "azure1"),
        legend.key = element_rect(fill = "white",
                                         color = "white"),
        # It added in blue behind the dots in the key and I don't want that
        panel.grid.major = element_line(size = 0.5, 
                                        linetype = 'solid', 
                                        colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid', 
                                        colour = "white")) # +
  # coord_quickmap() # This will fix the weird stretch usually, can also do coord_fixed(ratio = 1.3)

mapOCNMS
```

```{r Histogram Functions}
# Histogram function
histogram_fill <- function(df, var, binwidth, fill = "darkgray") {
  label <- rlang::englue("A histogram of {{var}} in {{df}} with binwidth {binwidth}")
  
  df |> 
    ggplot(aes(x = {{ var }}, fill = {{fill}})) + 
    geom_histogram(binwidth = binwidth, color = "black") + 
    labs(title = label) +
    theme_bw()
}

histogram2 <- function(df, var, binwidth, fill = NA) { # Not currently functional
  label <- rlang::englue("A histogram of {{var}} in {{df}} with binwidth {binwidth}")
  
  if (is.na(fill)) {
    df |> 
    ggplot(aes(x = {{ var }})) + 
    geom_histogram(binwidth = binwidth, color = "black", fill = "darkgray") + 
    labs(title = label) +
    theme_bw()
  } else {
  df |> 
    ggplot(aes(x = {{ var }}, fill = {{fill}})) + 
    geom_histogram(binwidth = binwidth, color = "black") + 
    labs(title = label) +
    theme_bw()
  }
  
}

histogram <- function(df, var, binwidth) {
  label <- rlang::englue("A histogram of {{var}} in {{df}} with binwidth {binwidth}")
  
  df |> 
    ggplot(aes(x = {{ var }})) + 
    geom_histogram(binwidth = binwidth, color = "black", fill = "darkgray") + 
    labs(title = label) +
    theme_bw()
}
```

```{r Scatterplot Functions}
# Function to speed up ggplot a little for basic data exploration
scatterplt <- function(df, x, y, shape = 16, alpha = 1) {
  label <- rlang::englue("A scatterplot of {{x}} vs {{y}} in {{df}}")
  
  df |> 
    ggplot(aes(x = {{ x }}, y = {{ y }})) + 
    geom_point(color = "blue", shape = shape, alpha = alpha) + 
    labs(title = label) +
    theme_bw()
}

scatterplt_fill <- function(df, x, y, color, shape = 16, alpha = 1) {
  label <- rlang::englue("A scatterplot of {{x}} vs {{y}} in {{df}}")
  
  df |> 
    ggplot(aes(x = {{ x }}, y = {{ y }}, color = {{ color }})) + 
    geom_point(shape = shape, alpha = alpha) + 
    labs(title = label) +
    theme_bw()
}
```

# Rename variables

```{r Rename Variables}
# Renname a few columns for consistency
TH042 <- TH042 %>% 
  rename(DO = oxy_mg, temperature = temp, salinity = sal, date = time, potential_density = dens)
```

# Data Exploration

All of these chunks are optional and can be used to explore the mooring data

## Histograms
```{r All Histograms, eval = F}
histogram_fill(TH042, depth, 0.5, fill = year) # Range 40-45 me
histogram_fill(TH042, temperature, 0.5, fill = year)
histogram_fill(TH042, salinity, 0.1, fill = year)
histogram_fill(TH042, potential_density, 0.1, fill = year)
histogram_fill(TH042, pres, 0.1, fill = year)
histogram_fill(TH042, DO, 0.1, fill = year)
```

## Scatterplots

```{r Scatterplots, eval = F}
scatterplt(TH042, potential_density, salinity, alpha = 0.1)
scatterplt_fill(TH042, potential_density, salinity, color = year)
```


# Oxygen Data Exploration

## Histograms
```{r Oxygen Histograms, eval = F}
histogram(TH042, DO, 0.5)

histogram(TH042, DO, 0.5) +
  facet_wrap(facets = vars(year), ncol = 1)

histogram_fill(TH042, DO, 0.5, fill = year) 
```

## Time Series

```{r, eval = F}
# Graph of oxygen levels around 42 meters for each year
TH042 %>% 
  ggplot(aes(x = date, y = DO, color = depth)) +
    geom_line() +
    geom_point(shape = 1) +
    theme_bw() +
    facet_wrap(facets = vars(year), scales = "free_x", ncol = 1)
ggsave("OCNMS_Mooring_Oxygen_FacetYear.png", path = here(pltpath), width = 3000, height = 4000, units = "px")
```

# Export

```{r Export Mooring Data}
# Add + reorder columns so that it can bind with the CTD data if desired
TH042$sampleID = NA
TH042$source = "Mooring"
TH042 <- TH042 %>% select("source", "date", "year", "temperature", "DO", "salinity", "potential_density", "pres", "cond", "sampleID") # Just ignoring depth since the mooring's depth reading changes with the currents, but it's always near 42m

write.csv(TH042, file = here("OCNMS_Hypoxia", "Outputs", "OCNMS_Mooring_CleanData.csv")) # Export file to hypoxia outputs
```

