---
title: "OCNMS Species Detection Data Cleaning"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
```

```{r}
SOI_IDs <- read_csv(here("OCNMS_eDNA", "Data", "All_SOI_IDs.csv")) # Identifications of species of interest
ref <- read_csv(here("OCNMS_eDNA", "Outputs", "FishPlusCOI_Reads.csv")) # Pivoted detection data + metadata, for reference
```

# Group by species, not ESV
```{r}
salmontest <- SOI_IDs %>% filter(Species == "Oncorhynchus kisutch")
# ESV and sample ID differ, need to group by both to avoid deleting dates
# Technical replicates may also differ
unique(salmontest) # Same size - good, no duplicates

# Filter out anything with 0 reads - this occurs due to the pivot, but isn't an actual detection
#SOI_ID2 <- SOI_IDs %>% 
#  filter(nReads != 0)

# I'm just gonna group by everything except ESV and sequence lmaooooo, basically all the data comes from SampleId x metadata anyway
SOI_ID_Species <- SOI_IDs %>% 
  group_by(Family, Genus, Species, JV_Sample_Name, Barcode.x, Barcode_mod, SampleId, Biological_Replicate, Technical_Replicate, Cruise_ID_short, Cast_No., Rosette_position, Field_collection_method, Preservation, Station, Depth_m, Field_Notes, Date_UTC, Date_local, Lat_dec, Lon_dec, Run, Client, Replicate, Amplicon, Barcode.y, Marker) %>% 
  summarize(TotalnReads = sum(nReads), avgpctMatch = mean(pctMatch)) %>%  # Result is smaller than SOI_ID2 - good!
  mutate(Present = case_when(TotalnReads == 0 ~ F, TotalnReads != 0 ~ T)) # Add presence/absence

SOI_ID_Species_Z <- SOI_IDs %>%  # Zack's suggested method
  group_by(Family, Genus, Species, JV_Sample_Name, Barcode.x, Barcode_mod, SampleId, Biological_Replicate, Technical_Replicate, Cruise_ID_short, Cast_No., Rosette_position, Field_collection_method, Preservation, Station, Depth_m, Field_Notes, Date_UTC, Date_local, Lat_dec, Lon_dec, Run, Client, Replicate, Amplicon, Barcode.y, Marker) %>% 
  summarize(TotalnReads = sum(nReads), avgpctMatch = mean(pctMatch)) %>%
  mutate(PA = if_else(TotalnReads >0, 1,0))
```


# Filter for >10 detections
```{r}
SOI_ID_Sp10 <- SOI_ID_Species %>% 
  group_by(Species) %>% 
  summarize(Detections = sum(Present)) %>%  # Spot check: 94 C. pallasii seems correct, 3 Anoplopoma fimbria is correct
  arrange(desc(Detections)) %>% 
  filter(Detections >= 10) # Generate list of species with >10 present observations
```

# Check against ref

```{r}
ref %>% 
  filter(Species == "Oncorhynchus tshawytscha") %>% # 665 rows
  filter(nReads != 0) %>% # 11 rows - presumably two from the same sample + different ESVs?
  group_by(SampleId) %>% 
  summarize(TotalnReads = sum(nReads)) # 10 samples have Oncorhynchus tshawytscha with more than 0 reads. This matches SOI_ID_Species! But unfortunately means we only have decent data for two species.
```

```{r}
# Zack check (modified)
ZCheck1 <- ref %>%
  mutate(PA = if_else(nReads >0, 1,0)) %>% 
  filter(PA > 0) %>% # Filter only for actual detections
  group_by(Species, SampleId) %>% # To distinguish separate detections
  count() %>% 
  group_by(Species) %>% 
  count() %>% 
  arrange(desc(n))

ZCheck <- ref %>%
  mutate(PA = if_else(nReads >0, 1,0)) %>% 
  filter(PA > 0) %>% # Filter only for actual detections
  filter(Species == "Oncorhynchus tshawytscha")
```


```{r}
SOI_ID_Sp_10Detect <- SOI_ID_Species %>% 
  filter(Species %in% SOI_ID_Sp10$Species) # Get all presence and absence data for species with >10 presence detections

write_csv(SOI_ID_Sp_10Detect, here("OCNMS_Project", "Outputs", "SOI_IDs_Species10Detections.csv"))
```


