---
title: "Environmental Data In Dates of Interest"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
```

```{r}
# Define dates of interest

BottleDates <- as.POSIXct(c("2021-08-25", "2022-06-21", "2022-08-22", "2022-09-20", "2021-10-08", "2022-07-19", "2023-06-15", "2023-07-26")) # Times from these are available
# seq() will take POSIXct objects, and by can be specified in seconds. Every 36 hours * * 60 minutes * 60 seconds = sampling every 129600 seconds

by1 <- 129600

PPS_Dates <- c(
  seq(from = as.POSIXct("2022-08-23"), by = by1, to = as.POSIXct("2022-09-18")), 
  seq(from = as.POSIXct("2021-08-26"), by = by1, to = as.POSIXct("2021-09-29")), 
  seq(from = as.POSIXct("2022-06-23"), by = by1, to = as.POSIXct("2022-07-19")), 
  seq(from = as.POSIXct("2023-06-16"), by = by1, to = as.POSIXct("2023-07-20"))
  )

Source <- "Bottle"
BottleDatesDF <- data.frame(Source, BottleDates) %>% rename(Date = BottleDates)
Source <- "PPS"
PPS_DatesDF <- data.frame(Source, PPS_Dates) %>% rename(Date = PPS_Dates)
DatesOfInterest <- rbind(BottleDatesDF, PPS_DatesDF)
# This can now be used for filtering joins :)

write.csv(DatesOfInterest, file = here("OCNMS_Project", "Data", "SamplingDates.csv"))
```

```{r}
MooringCTD_Data <- read.csv(here("OCNMS_Hypoxia", "Outputs", "EnvironmentalDataset1.csv")) # Import mooring and CTD environmental data from 2021-2023 + 30-45 meters deep
MooringCTD_Data$date <- as.POSIXct(MooringCTD_Data$date)
```

```{r}
ggplot(MooringCTD_Data, aes(x = date, y = temperature, color = source)) +
  geom_point() +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m-%y") +
  theme_bw() +
  facet_wrap(facets = vars(year), scales = "free_x", ncol = 1) +
  geom_vline(data = DatesOfInterest, aes(xintercept = Date, color = Source)) +
  scale_color_manual(values = c("purple1", "blue", "skyblue2", "purple4"))

ggplot(MooringCTD_Data, aes(x = date, y = DO, color = source)) +
  geom_point() +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m-%y") +
  theme_bw() +
  facet_wrap(facets = vars(year), scales = "free_x", ncol = 1) +
  geom_vline(data = DatesOfInterest, aes(xintercept = Date, color = Source)) +
  scale_color_manual(values = c("purple1", "blue", "skyblue2", "purple4")) +
  geom_hline(aes(yintercept = 2), color = "red") +
  labs(caption = "Red line = hypoxic threshold of 2 mg/L dissolved oxygen")
ggsave(here("OCNMS_Hypoxia", "Plots", "OxygenOverDeploymentWindows.png"))
```

