---
title: "WORRMS Package/Species of Interest Cleaning"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
library(worrms)
library(taxonomizr)
```

# Import species of interest from Shannon

```{r}
SOI_df <- read.csv(here("OCNMS_eDNA", "Data", "OCNMS_SpeciesOfInterest.csv"))
genera <- c("Pseudo-nitzchia", "Pyrosoma", "Pyrosomella", "Sargassum", "Undaria", "Acrozoanthus", "Isarus", "Zoanthus")
families <- c("Ammodytidae", "Acipenseridae")
othernote <- "Pteropods, Northern copepods"
SpeciesOfInterest <- c(SOI_df$Taxon, "Cancer magister", "Haliotis kamtschatkana kamtschatkana", "Haliotis assimilis") # FUll list of species-specific targest. Includes some not accepted old names.
```

# Import eDNA combined data

```{r}
fishReads <- read.csv(here("OCNMS_eDNA", "Data", "OCNMS_MiFish_Data.csv"))
fishReads <- fishReads %>% 
  mutate(Marker = "MiFish")

kelReads <- read.csv(here("OCNMS_eDNA", "Data", "OCNMS_Kelly_Data.csv"))
kelReads <- kelReads %>% 
  mutate(Marker = "Kelly16S")

coiReads <- read.csv(here("OCNMS_eDNA", "Data", "OCNMS_COI_Data.csv"))
coiReads <- coiReads %>% 
  mutate(Marker = "Uni_CO1")
```

# Single species example

```{r}
# Pull Aphia ID
AphiaID <- wm_name2id("Engraulis mordax") # With underscore = list of names, without underscore = one name
# Get NCBI taxonomy ID
wm_external(AphiaID, type = "ncbi")
# Plug that into NCBI and you can pull the taxonomy to see if that name is in the dataset - use taxonKit
# taxonKit is a command line tool
# taxonkit lineage 239368.txt

# or do taxonomizr - still requires NCBI database to be downloaded on computer 
#> prepareDatabase('accessionTaxa.sql')
getTaxonomy(239368, here("accessionTaxa.sql"))
```

# All species of interest script

```{r}

```

# Export species of interest

```{r}
# write.csv(df, here("OCNMS_eDNA", "Data", "OCNMS_SpeciesOfInterest_Clean.csv"))
```


