---
title: "phyloseq Testing"
author: "Ella Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
---

```{r Package Imports}
library(igraph)
library(phyloseq) 
# Problem
# Google says it depends on "igraph"
# Actual problem was that it needed BiocManager
library(vegan)
library(ggplot2)
```

# [Documentation Link](https://alexiscarter.github.io/metab/Phyloseq_script.html)

# Make a phyloseq object

```
ps <- phyloseq(otu_table(ASV table, taxa_are_rows=FALSE), 
               sample_data(Sample Data), 
               tax_table(as.matrix(Taxonomy Table$Taxon)))
```

# Subset by taxa

`ps.fungi = subset_taxa(ps, Kingdom==k__Fungi")`

# Data transformation functions
Phyloseq has a variety of data cleaning and transformation functions.

Data exploration functions:

- `ntaxa()`
- `nsamples()`
- `rank_names()` lists the taxonomic levels represented
- `sample_variables()`
- `otu_table()`
- `tax_table()`

# Plotting functions

- `plot_bar(ps, x = "Sample", y = "Abundance", fill = pick a taxon level, ex. "Phylum")` $\leftarrow$ This is a ggplot object that can be added to
- `plot_ordination(agglomerated sp, ordered sp, type = "samples", color = "horizon")` quick plots NMDS for clustering
  - This can get more complicated and you can draw `stat_ellipse()` for clustering


The function `ordinate()` can be used to order by dissimilarity

# Variance analysis

```
metadata <- as(sample_data(ps.fungi.nosd.log.sp), "data.frame") # Export data

adonis(phyloseq::distance(physeq = ps.fungi.nosd.log.sp, method="bray") ~ horizon * forest, strata = metadata$block, # PERMANOVA parameters
  data = metadata,
  permutations = 99999)
```

- `betadisper()` tests for dipsersion homogeneity using different methods, including `method = "bray"` for Bray-Curtis dissimilarity
- `ordinate()` can be used with Redundancy Analysis (RDA). `ord.rda <- ordinate(ps.fungi.nosd.log.sp, formula = , method = , distance = )`, then `RsquareAdj(ord.rda)` and `anova.cca(ord.rda)`
- `vif.cca(ord.rda)` checks for Variance Inflation Factors, VIF < 10 should be fine 
  - `plot_ordination()` can also plot RDA 
  - ord.rda has eigenvectors in it