---
title: "OCNMS eDNA Metadata Cleaning"
author: "Eleanor (Ella) Crotty"
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: TRUE
urlcolor: blue
---

```{r Package Imports, message = F, warning = F}
# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
library(measurements)
library(sp)
```

# Define species of interest
```{r}
here::i_am("PMEL-Hollings-eDNA-Hypoxia-2024.Rproj") # Set working directory to further up in the repo
here()
SOI_df <- read.csv(here("OCNMS_eDNA", "Data", "OCNMS_SpeciesOfInterest_Short.csv"))
SOI_other_df <- read.csv(here("OCNMS_eDNA", "Data", "OCNMS_OtherOfInterest.csv"))
genera <- c("Pseudo-nitzchia", "Pyrosoma", "Pyrosomella", "Sargassum", "Undaria", "Acrozoanthus", "Isarus", "Zoanthus")
families <- c("Ammodytidae", "Acipenseridae")
othernote <- "Pteropods, Northern copepods"
SpeciesOfInterest <- c(SOI_df$Taxon, "Cancer magister", "Haliotis kamtschatkana kamtschatkana", "Haliotis assimilis") # Includes some not accepted old names
# Reset to normal here so I can run other stuff in this script
here::i_am("OCNMS.Rproj") 
```

# Import metadata
```{r}
here()
JV_Data <- read.csv(here("JV243.2_sampleData.csv"), header = T)

sample_Data <- read.csv(file = here("20240621_OCNMS_eDNA_sampleData_zjg.csv"), header=T,fileEncoding="UTF-8")
```

# Clean metadata
```{r}
sample_Data %>% 
  filter(., str_detect(Sample_Name,"OC")) %>% # Filter for only OCNMS samples
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC), # Several steps from Zack to fix datetime
         Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%y %H:%M", tz="UTC"),
         Date_local = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="America/Los_Angeles")) %>%
  mutate(., Date_local_check= format(Date_UTC,tz="America/Los_Angeles"),
                  Date_UTC_check= format(Date_local,tz="GMT")) %>% 
   mutate(.,      Date_local_check= as.POSIXct(Date_local_check, format="%Y-%m-%d %H:%M:%S", tz="America/Los_Angeles"),
         Date_UTC_check= as.POSIXct(Date_UTC_check, format="%Y-%m-%d %H:%M:%S", tz="UTC")) %>% 
  mutate(.,Date_UTC = case_when(is.na(Date_UTC) ~ Date_UTC_check,
                                TRUE ~ Date_UTC),
           Date_local = case_when(is.na(Date_local) ~ Date_local_check,
                                TRUE ~ Date_local)) %>% 
  dplyr::select(-Date_UTC_check,-Date_local_check) -> time_cor_ocnms
```

```{r}
OCNMS_sample_metadata <- time_cor_ocnms %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% # Several steps from Zack to convert degrees/feet to decimal degrees
    mutate(., Lat_fix =str_replace(Lat_fix, "˚","")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "˚","")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lat_dec=as.double(Lat_dec),
         Lon_dec=as.double(Lon_dec)) %>% 
    mutate(., Lon_dec = Lon_dec*-1) %>% 
  mutate(., Lat_dec = case_when(is.na(Lat_dec_sean) ~ Lat_dec,
                                TRUE ~Lat_dec_sean ),
         Lon_dec = case_when(is.na(Lat_dec_sean) ~ Lon_dec,
                                TRUE ~Lon_dec_sean )) %>% 
  left_join(., JV_Data, by=c("Sample_Name"="OwnerSampleId")) %>% # Attach metadata by E number
  select(-c(Lat, Lon, Lat_dec_sean, Lon_dec_sean, Lat_fix, Lon_fix, Combined_date, Combined_date_local, Collection_Date_UTC, Collection_Date_local, Collection_Time_UTC, Collection_Time_local)) # Delete all the nonsense generated by the coordinate fixing, and all the date and time columns except the final ones
```

# Import sequence data

## MiFish
```{r}
# Combine with mifish data
mifish_data <- read.csv(here("JV_bioinformatics","JVB3041_export","MiFishU_F2","MiFishU_F2_tab+taxa.csv"), header = T)
# colnames(mifish_data)
mifish_data <- mifish_data %>% # Cleaning 
  select(-c(flagged, numSpp)) %>% # Zack said I could ignore numSpp
  filter(Family != "") # If it's not identified to the family level it's not useful to me
```

```{r}
# How many species and samples in mifish?
mifish_data %>% 
  group_by(Species) %>% 
  summarize(n = n()) # 98 species

mifish_data %>% 
  group_by(ESV) %>% 
  summarize(n = n()) # 810 ESVs
# How many samples? Cols 13 to 390, 378 samples
samples <- 390-12
samples * 98 # = 37044, so that's how many rows the pivoted data should have
samples * 810 # = 306180, so that's how many rows the pivoted data should have (where did an extra 6000 observations come from?)
```


```{r}
mifish_pivot <- mifish_data %>% 
  pivot_longer(cols=`JV243.2_MiFishU_F2_GoldZachary_S074400.1`:`JV243.2_MiFishU_F2_GoldZachary_S074783.1`, names_to = "JV_Sample_Name", values_to = "nReads") # Make sample numbers rows, not columns

mifish_pivot %>% 
separate(JV_Sample_Name, into=c("JV243.2","Barcode","Barcode_mod","PI","SampleId"), sep="_", remove=F) %>% # Extract SampleID from JV_Sample_Name so that it can be matched by E-number
  mutate(., SampleId=str_sub(SampleId,end=-3)) -> holder # Zack fix

OCNMS_sample_metadata %>% 
  filter(., Amplicon =="MiFishU_F2") -> OCNMS_sample_metadata_mf

holder %>% # Zack fix
  left_join(OCNMS_sample_metadata_mf, by="SampleId") -> combined_data_mf # This currently exceeds the memory space allocated to R

combined_data_mf
```

## Kelly 16S

```{r}
# Combine with Kelly 16S data
kelly_data <- read.csv(here("JV_bioinformatics","JVB3041_export","16SKelly","16SKelly_tab+taxa.csv"), header = T)
colnames(kelly_data)
kelly_data <- kelly_data %>% # Cleaning 
  select(-c(flagged, numSpp)) %>% 
  filter(Family != "") # If it's not identified to the family level it's not useful to me
```
# Haven't applied the metadata filtering fix here yet! Can't find the Kelly primer in there

```{r}
kelly_data %>% 
  pivot_longer(cols=`JV243.2_16SKelly_GoldZachary_S076040.1`:`JV243.2_16SKelly_GoldZachary_S076125.1`, names_to = "JV_Sample_Name", values_to = "nReads") %>% # All of the bottle columns - this is currently generating a warning saying there are a lot of missing pieces due to a many-to-many relationship between x and y
separate(JV_Sample_Name, into=c("JV243.2","Barcode","Barcode_mod","PI","SampleId"), sep="_", remove=F) %>% mutate(., SampleId=str_sub(SampleId,end=-3)) %>% 
  left_join(OCNMS_sample_metadata, by="SampleId") -> combined_data_k
```

## COI

```{r}
# Combine with COI data
coi_data <- read.csv(here("JV_bioinformatics","JVB3041_export","UniCOI","UniCOI_tab+taxa.csv"), header = T)
# colnames(coi_data)
genera <- c("Pseudo-nitzchia", "Pyrosoma", "Pyrosomella", "Sargassum", "Undaria", "Acrozoanthus", "Isarus", "Zoanthus")
families <- c("Ammodytidae", "Acipenseridae") # If it's not in here and Genus = "" then I don't want it
coi_data <- coi_data %>% # Cleaning to try to not exhaust vector memory
  select(-c(flagged, numSpp)) %>% 
  filter(Genus %in% genera | Family %in% families | Species != "") # If it's not identified to the species level or in one of these specific families/genera, it's not useful to me.

coi_data <- coi_data %>% 
  filter(Species != "Homo sapiens") # contamination
```

```{r}
#coi_data <- coi_data %>% 
#  filter(!Species %in% rarespeciescoi)

coi_data %>% 
  group_by(ESV) %>% 
  mutate(nreads = rowSums(pick(`JV243.2_UniCOI_GoldZachary_S074016.1`:`JV243.2_UniCOI_GoldZachary_S074399.1`))) %>% 
  relocate(nreads, .before = `JV243.2_UniCOI_GoldZachary_S074016.1`)
```

```{r}
coi_data %>% 
  pivot_longer(cols=`JV243.2_UniCOI_GoldZachary_S074016.1`:`JV243.2_UniCOI_GoldZachary_S074399.1`, 
               names_to = "JV_Sample_Name", 
               values_to = "nReads") %>% # All of the bottle columns - this is currently generating a warning saying there are a lot of missing pieces due to a many-to-many relationship between x and y
  separate(JV_Sample_Name,
           into=c("JV243.2","Barcode","Barcode_mod","PI","SampleId"), 
           sep="_", 
           remove=F) %>% 
  mutate(., SampleId=str_sub(SampleId,end=-3)) -> holder # Zack fix

OCNMS_sample_metadata %>% 
  filter(., Amplicon =="UniCOI") -> OCNMS_sample_metadata_coi

holder %>% # Zack fix
  left_join(OCNMS_sample_metadata_coi, by="SampleId") -> combined_data_coi # This currently exceeds the memory space allocated to R

saveRDS(combined_data_coi, file=here("eDNA_merged","combined_data_co1.RDS"))
```

```{r}
# Check it out
combined_data_mf %>% 
  filter(., nReads >0) %>% 
  group_by(ESV) %>% 
  count() %>% 
  arrange(desc(n))
```


```{r}
# Export to this folder
here::i_am("OCNMS.Rproj")
here()

write.csv(OCNMS_sample_metadata, here("OCNMS_eDNA_sampleData_Full2.csv")) # Save to Zack OCNMS outputs
#write.csv(combined_data_mf, here("OCNMS_eDNA_MiFish_Data2.csv")) # Save to Zack OCNMS outputs
#write.csv(combined_data_k, here("OCNMS_eDNA_Kelly_Data2.csv")) # Save to Zack OCNMS outputs
#write.csv(combined_data_coi, here("OCNMS_eDNA_COI_Data2.csv")) # Save to Zack OCNMS outputs

# Export to the eDNA project folder
here::i_am("PMEL-Hollings-eDNA-Hypoxia-2024.Rproj") # Set working directory to further up in the repo
here()

write.csv(OCNMS_sample_metadata, here("OCNMS_eDNA", "Data", "OCNMS_eDNA_sampleData_Full.csv")) # Also save to eDNA inputs
write.csv(combined_data_mf, here("OCNMS_eDNA", "Data", "OCNMS_MiFish_Data.csv")) # Also save to eDNA inputs
write.csv(combined_data_k, here("OCNMS_eDNA", "Data", "OCNMS_Kelly_Data.csv")) # Also save to eDNA inputs
write.csv(combined_data_coi, here("OCNMS_eDNA", "Data", "OCNMS_COI_Data.csv")) # Also save to eDNA inputs

# Reset to normal here so I can run other stuff in this script
here::i_am("OCNMS.Rproj") 
```



