# Warnings and startup messages suppressed
library(tidyverse)
library(patchwork)
library(scales)
library(ggrepel)
library(readxl)
library(here)
library(measurements)
library(sp)

JV_Data <- read.csv(here("JV243.2_sampleData.csv"), header = T)
here()

sample_Data <- read.csv(file = here("20240621_OCNMS_eDNA_sampleData_zjg.csv"), header=T,fileEncoding="UTF-8")


sample_Data %>% 
  filter(., str_detect(Sample_Name,"OC")) %>% # Filter for only OCNMS samples
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC), # Several steps from Zack to fix datetime
         Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%y %H:%M", tz="UTC"),
         Date_local = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="America/Los_Angeles")) %>%
  mutate(., Date_local_check= format(Date_UTC,tz="America/Los_Angeles"),
         Date_UTC_check= format(Date_local,tz="GMT")) %>% 
  mutate(.,      Date_local_check= as.POSIXct(Date_local_check, format="%Y-%m-%d %H:%M:%S", tz="America/Los_Angeles"),
         Date_UTC_check= as.POSIXct(Date_UTC_check, format="%Y-%m-%d %H:%M:%S", tz="UTC")) %>% 
  mutate(.,Date_UTC = case_when(is.na(Date_UTC) ~ Date_UTC_check,
                                TRUE ~ Date_UTC),
         Date_local = case_when(is.na(Date_local) ~ Date_local_check,
                                TRUE ~ Date_local)) %>% 
  dplyr::select(-Date_UTC_check,-Date_local_check) -> time_cor_ocnms


OCNMS_sample_metadata <- time_cor_ocnms %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% # Several steps from Zack to convert degrees/feet to decimal degrees
  mutate(., Lat_fix =str_replace(Lat_fix, "˚","")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
  mutate(., Lon_fix =str_replace(Lon_fix, "˚","")) %>%
  mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lat_dec=as.double(Lat_dec),
         Lon_dec=as.double(Lon_dec)) %>% 
  mutate(., Lon_dec = Lon_dec*-1) %>% 
  mutate(., Lat_dec = case_when(is.na(Lat_dec_sean) ~ Lat_dec,
                                TRUE ~Lat_dec_sean ),
         Lon_dec = case_when(is.na(Lat_dec_sean) ~ Lon_dec,
                             TRUE ~Lon_dec_sean )) %>% 
  left_join(., JV_Data, by=c("Sample_Name"="OwnerSampleId")) %>% # Attach metadata by E number
  select(-c(Lat, Lon, Lat_dec_sean, Lon_dec_sean, Lat_fix, Lon_fix, Combined_date, Combined_date_local, Collection_Date_UTC, Collection_Date_local, Collection_Time_UTC, Collection_Time_local)) # Delete all the nonsense generated by the coordinate fixing, and all the date and time columns except the final ones


# Combine with mifish data
mifish_data <- read.csv(here("JV_bioinformatics","JVB3041_export","MiFishU_F2","MiFishU_F2_tab+taxa.csv"), header = T)
colnames(mifish_data)
mifish_data <- mifish_data %>% # Cleaning 
  select(-c(flagged, numSpp)) %>% # Zack said I could ignore numSpp
  filter(Family == "") # If it's not identified to the family level it's not useful to me

mifish_data %>% 
  pivot_longer(cols=`JV243.2_MiFishU_F2_GoldZachary_S074400.1`:`JV243.2_MiFishU_F2_GoldZachary_S074783.1`, names_to = "JV_Sample_Name", values_to = "nReads") %>% 
  separate(JV_Sample_Name, into=c("JV243.2","Barcode","Barcode_mod","PI","SampleId"), sep="_", remove=F) %>% mutate(., SampleId=str_sub(SampleId,end=-3)) %>% 
  left_join(OCNMS_sample_metadata, by="SampleId") -> combined_data_mf

combined_data_mf


# Combine with Kelly 16S data
kelly_data <- read.csv(here("JV_bioinformatics","JVB3041_export","16SKelly","16SKelly_tab+taxa.csv"), header = T)
colnames(kelly_data)
kelly_data <- kelly_data %>% # Cleaning 
  select(-c(flagged, numSpp)) %>% 
  filter(Family == "") # If it's not identified to the family level it's not useful to me

kelly_data %>% 
  pivot_longer(cols=`JV243.2_16SKelly_GoldZachary_S076040.1`:`JV243.2_16SKelly_GoldZachary_S076125.1`, names_to = "JV_Sample_Name", values_to = "nReads") %>% # All of the bottle columns - this is currently generating a warning saying there are a lot of missing pieces due to a many-to-many relationship between x and y
  separate(JV_Sample_Name, into=c("JV243.2","Barcode","Barcode_mod","PI","SampleId"), sep="_", remove=F) %>% mutate(., SampleId=str_sub(SampleId,end=-3)) %>% 
  left_join(OCNMS_sample_metadata, by="SampleId") -> combined_data_k


# Combine with COI data
coi_data <- read.csv(here("JV_bioinformatics","JVB3041_export","UniCOI","UniCOI_tab+taxa.csv"), header = T)
colnames(coi_data)
genera <- c("Pseudo-nitzchia", "Pyrosoma", "Pyrosomella", "Sargassum", "Undaria", "Acrozoanthus", "Isarus", "Zoanthus")
families <- c("Ammodytidae", "Acipenseridae") # If it's not in here and Genus = "" then I don't want it
coi_data <- coi_data %>% # Cleaning to try to not exhaust vector memory
  select(-c(flagged, numSpp)) %>% 
  filter(Genus %in% genera | Family %in% families | Species != "") # If it's not identified to the species level or in one of these specific families/genera, it's not useful to me.

coi_data %>% 
  pivot_longer(cols=`JV243.2_UniCOI_GoldZachary_S074016.1`:`JV243.2_UniCOI_GoldZachary_S074399.1`, names_to = "JV_Sample_Name", values_to = "nReads") %>% # All of the bottle columns - this is currently generating a warning saying there are a lot of missing pieces due to a many-to-many relationship between x and y
  separate(JV_Sample_Name, into=c("JV243.2","Barcode","Barcode_mod","PI","SampleId"), sep="_", remove=F) %>% mutate(., SampleId=str_sub(SampleId,end=-3)) %>% 
  left_join(OCNMS_sample_metadata, by="SampleId") -> combined_data_coi
